// ═══════════════════════════════════════════════════════════════════════
// src/lib/clinical/orthopedicTests/lowerLimb.ts
// ═══════════════════════════════════════════════════════════════════════
// Test ortopedici arto inferiore: anca, ginocchio, caviglia/piede.
// Fonti: Magee 6th ed., Cook & Hegedus, Physiopedia, Reiman et al.
// ═══════════════════════════════════════════════════════════════════════

import type { OrthopedicTest } from "./types";

export const LOWER_LIMB_TESTS: OrthopedicTest[] = [

  // ═════ ANCA ════════════════════════════════════════════════════
  {
    name: "FADIR",
    district: "hip",
    purpose: "Identifica impingement femoro-acetabolare anteriore (FAI) o lesione del labbro.",
    procedure: "Paziente supino. Flessione dell'anca a 90°, adduzione e rotazione interna massimali.",
    positive: "Dolore inguinale o click = impingement femoro-acetabolare anteriore (FAI).",
    sensitivity: "78-94%", specificity: "10-25%", source: "Reiman et al. 2015 (meta-analisi)",
    aliases: ["Anterior impingement test"],
  },
  {
    name: "FABER (Patrick) — anca",
    district: "hip",
    purpose: "Valuta patologia intra-articolare d'anca o sacroiliaca.",
    procedure: "Posizione 'numero 4': flessione, abduzione ed extra-rotazione dell'anca. L'esaminatore applica pressione sul ginocchio flesso e sulla EIAS opposta.",
    positive: "Dolore inguinale = patologia intra-articolare d'anca. Posteriore = sacroiliaca.",
    sensitivity: "60-82%", specificity: "18-25%",
  },
  {
    name: "Trendelenburg",
    district: "hip",
    purpose: "Valuta forza dei muscoli abduttori dell'anca (medio gluteo).",
    procedure: "Paziente in piedi. Si chiede di sollevare un arto inferiore (stare su una gamba sola) per 30 secondi.",
    positive: "Caduta del bacino dal lato sollevato = debolezza dei muscoli abduttori dell'anca portante.",
    sensitivity: "73%", specificity: "77%", source: "Bird et al. 2001",
  },
  {
    name: "Thomas",
    district: "hip",
    purpose: "Valuta retrazione dei flessori dell'anca (ileopsoas, retto femorale).",
    procedure: "Paziente supino. Una gamba flessa al petto, l'altra estesa sul lettino. Si osserva la posizione della coscia estesa.",
    positive: "La coscia non resta a contatto col lettino = retrazione dell'ileopsoas. Ginocchio esteso = retrazione del retto femorale.",
    sensitivity: "89%", specificity: "92%", source: "Harvey 1998",
  },
  {
    name: "Ober",
    district: "hip",
    purpose: "Valuta retrazione della bandelletta ileo-tibiale e tensore della fascia lata.",
    procedure: "Paziente in decubito laterale. L'esaminatore solleva l'arto superiore in abduzione ed estensione, poi lo rilascia (con ginocchio flesso a 90°).",
    positive: "L'arto rimane in abduzione e non scende = retrazione della bandelletta ileotibiale o TFL.",
  },
  {
    name: "Ely",
    district: "hip",
    purpose: "Valuta retrazione del retto femorale.",
    procedure: "Paziente prono. L'esaminatore flette passivamente il ginocchio portando il tallone al gluteo.",
    positive: "Sollevamento del bacino dal lettino = retrazione del retto femorale.",
  },
  {
    name: "Anterior Apprehension d'anca",
    district: "hip",
    purpose: "Identifica instabilità anteriore d'anca / lassità capsulare.",
    procedure: "Paziente prono. L'esaminatore estende l'anca, abduce e ruota esternamente.",
    positive: "Apprehension o dolore anteriore = instabilità anteriore d'anca.",
    sensitivity: "57%", specificity: "80%",
  },
  {
    name: "Log Roll test",
    district: "hip",
    purpose: "Test per patologia intra-articolare d'anca (specifico per articolare).",
    procedure: "Paziente supino con anche neutre. L'esaminatore ruota passivamente la gamba internamente ed esternamente.",
    positive: "Dolore o click intra-articolare = patologia intra-articolare d'anca.",
    sensitivity: "30%", specificity: "100%", source: "Reiman et al. 2015",
  },
  {
    name: "Hip Scour (Quadrant test)",
    district: "hip",
    purpose: "Valuta patologia intra-articolare dell'anca.",
    procedure: "Paziente supino. Flessione dell'anca a 90°, compressione assiale lungo il femore, movimento in adduzione/abduzione + rotazioni.",
    positive: "Riproduzione di dolore intra-articolare = patologia dell'anca.",
    sensitivity: "62%", specificity: "75%",
  },
  {
    name: "Resisted Straight Leg Raise (Stinchfield)",
    district: "hip",
    purpose: "Valuta patologia intra-articolare d'anca (cartilaginea, labbrale).",
    procedure: "Paziente supino, anca flessa a 30°. Si resiste la flessione attiva dell'anca.",
    positive: "Dolore inguinale = patologia intra-articolare d'anca.",
    sensitivity: "59%", specificity: "32%",
    aliases: ["Stinchfield test"],
  },
  {
    name: "Single Leg Stance test (hip)",
    district: "hip",
    purpose: "Valuta dolore d'anca durante carico monopodalico.",
    procedure: "Paziente in piedi su una gamba per 30 secondi.",
    positive: "Dolore inguinale o laterale d'anca = patologia (FAI, tendinopatia glutea).",
    sensitivity: "100%", specificity: "97%", source: "Lequesne et al. 2008 (per tendinopatia glutea)",
  },
  {
    name: "Adductor squeeze",
    district: "hip",
    purpose: "Valuta patologia del tendine adduttori (pubalgia atletica).",
    procedure: "Paziente supino, anche flesse a 45° e ginocchia a 90°. L'esaminatore inserisce un pugno tra le ginocchia. Si chiede di stringere.",
    positive: "Dolore in regione inguinale/adduttori = lesione/tendinopatia adduttori.",
    sensitivity: "43%", specificity: "91%", source: "Verrall et al. 2005",
  },
  {
    name: "Piriformis test (FAIR)",
    district: "hip",
    purpose: "Identifica sindrome del piriforme (compressione del nervo sciatico).",
    procedure: "Paziente in decubito laterale o seduto. Flessione, adduzione e rotazione interna passiva dell'anca.",
    positive: "Dolore al gluteo o sciatalgia = sindrome del piriforme.",
    sensitivity: "60%", specificity: "67%", source: "Fishman et al. 2002",
    aliases: ["FAIR test"],
  },
  {
    name: "Pace's sign",
    district: "hip",
    purpose: "Identifica sindrome del piriforme con resistenza all'abduzione.",
    procedure: "Paziente seduto. Si resiste l'abduzione ed extra-rotazione dell'anca.",
    positive: "Dolore al gluteo = sindrome del piriforme.",
    sensitivity: "30%", specificity: "Variabile",
  },
  {
    name: "Posterior Hip Capsular Tenderness",
    district: "hip",
    purpose: "Conferma FAI insieme al FADIR (aumenta accuratezza diagnostica).",
    procedure: "Decubito laterale, anca flessa a 20°. Palpazione 5 cm posteriore e 2 cm superiore al grande trocantere.",
    positive: "Dolore alla palpazione = irritazione capsulare posteriore (FAI).",
    sensitivity: "71%", specificity: "82%", source: "Yang et al. 2023 (con FADIR)",
  },

  // ═════ GINOCCHIO — LCA ═══════════════════════════════════════════
  {
    name: "Lachman",
    district: "knee",
    purpose: "Identifica lesione del legamento crociato anteriore (LCA) — gold standard.",
    procedure: "Paziente supino, ginocchio a 20-30° di flessione. L'esaminatore stabilizza il femore con una mano e trae la tibia anteriormente con l'altra.",
    positive: "Aumentata traslazione anteriore della tibia con endpoint molle = lesione del LCA.",
    sensitivity: "85%", specificity: "94%", source: "Benjaminse et al. 2006 (meta-analisi)",
  },
  {
    name: "Drawer test anteriore",
    district: "knee",
    purpose: "Identifica lesione del LCA (meno sensibile del Lachman).",
    procedure: "Paziente supino, ginocchio a 90° di flessione, piede stabilizzato. L'esaminatore afferra la tibia prossimale e tira anteriormente.",
    positive: "Aumentata traslazione anteriore della tibia rispetto al lato controlaterale = lesione del LCA.",
    sensitivity: "55%", specificity: "92%", source: "Benjaminse et al. 2006",
  },
  {
    name: "Pivot Shift",
    district: "knee",
    purpose: "Identifica instabilità rotatoria del ginocchio in lesione del LCA.",
    procedure: "Paziente supino, ginocchio in estensione. L'esaminatore applica valgismo e rotazione interna alla tibia mentre flette progressivamente il ginocchio.",
    positive: "Riduzione palpabile della sublussazione tibiale tra 20°-40° di flessione = lesione del LCA. Alta specificità.",
    sensitivity: "24%", specificity: "98%", source: "Benjaminse et al. 2006",
  },
  {
    name: "Lever sign (Lelli)",
    district: "knee",
    purpose: "Test recente per LCA, valido anche su pazienti acuti/dolorosi.",
    procedure: "Paziente supino, gamba estesa. L'esaminatore pone il pugno sotto il polpaccio (terzo prossimale) e applica una forza verso il basso sulla coscia.",
    positive: "Il tallone non si solleva dal lettino = lesione del LCA.",
    sensitivity: "63-100%", specificity: "80-100%", source: "Lelli et al. 2016",
  },

  // ═════ GINOCCHIO — LCP ═══════════════════════════════════════════
  {
    name: "Drawer posteriore",
    district: "knee",
    purpose: "Identifica lesione del legamento crociato posteriore (LCP).",
    procedure: "Paziente supino, ginocchio a 90° di flessione, piede stabilizzato. L'esaminatore afferra la tibia prossimale e spinge posteriormente.",
    positive: "Aumentata traslazione posteriore della tibia = lesione del LCP.",
    sensitivity: "90%", specificity: "99%", source: "Rubinstein et al. 1994",
  },
  {
    name: "Posterior Sag sign (Godfrey)",
    district: "knee",
    purpose: "Identifica lesione del LCP.",
    procedure: "Paziente supino, anche e ginocchia a 90°. L'esaminatore sostiene i talloni e osserva il profilo tibiale.",
    positive: "Tibia che 'cade' posteriormente rispetto al femore = lesione del LCP.",
    sensitivity: "79%", specificity: "100%",
  },
  {
    name: "Quadriceps Active Test",
    district: "knee",
    purpose: "Identifica lesione del LCP con contrazione attiva.",
    procedure: "Paziente supino, ginocchio a 90°, piede stabilizzato. Si chiede di contrarre il quadricipite.",
    positive: "Spostamento anteriore della tibia dalla posizione di 'sag' = lesione del LCP.",
    sensitivity: "98%", specificity: "100%",
  },

  // ═════ GINOCCHIO — MENISCHI ═════════════════════════════════════
  {
    name: "McMurray",
    district: "knee",
    purpose: "Identifica lesione meniscale.",
    procedure: "Paziente supino, ginocchio in massima flessione. Per menisco mediale: extra-rotazione tibiale + valgismo + estensione. Per laterale: intra-rotazione + varismo + estensione.",
    positive: "Click o dolore lungo l'interlinea articolare = lesione meniscale.",
    sensitivity: "61%", specificity: "84%", source: "Hegedus et al. 2007",
  },
  {
    name: "Apley compression/distraction",
    district: "knee",
    purpose: "Differenzia lesioni meniscali da legamentose.",
    procedure: "Paziente prono, ginocchio a 90°. Compressione: forza assiale + rotazione tibiale. Distrazione: trazione + rotazione.",
    positive: "Compressione: dolore o click = lesione meniscale. Distrazione: dolore = lesione legamentosa.",
    sensitivity: "60%", specificity: "70%",
  },
  {
    name: "Thessaly",
    district: "knee",
    purpose: "Identifica lesione meniscale durante carico (sensibile).",
    procedure: "Paziente in piedi su una gamba (lato testato), ginocchio a 20° di flessione. Si chiede di ruotare il bacino e il corpo internamente/esternamente 3 volte.",
    positive: "Dolore lungo l'interlinea = lesione meniscale (mediale o laterale a seconda della rotazione).",
    sensitivity: "65-94%", specificity: "67-96%", source: "Karachalios et al. 2005",
  },
  {
    name: "Joint Line Tenderness",
    district: "knee",
    purpose: "Test palpatorio per lesione meniscale.",
    procedure: "Paziente supino, ginocchio flesso a 90°. Palpazione dell'interlinea articolare mediale e laterale.",
    positive: "Dolore alla palpazione dell'interlinea = lesione meniscale.",
    sensitivity: "76%", specificity: "29%", source: "Eren 2003",
  },
  {
    name: "Ege's test",
    district: "knee",
    purpose: "Test in carico per lesione meniscale.",
    procedure: "Paziente in piedi a piedi divaricati 30-40 cm. Per menisco mediale: piedi extra-ruotati, accosciata. Per laterale: piedi intra-ruotati, accosciata.",
    positive: "Click o dolore durante l'accosciata = lesione meniscale.",
    sensitivity: "67-76%", specificity: "81-89%", source: "Akseki et al. 2004",
  },

  // ═════ GINOCCHIO — LCM/LCL ═════════════════════════════════════
  {
    name: "Valgo stress test",
    district: "knee",
    purpose: "Valuta integrità del legamento collaterale mediale (LCM).",
    procedure: "Paziente supino, ginocchio a 0° e poi a 30° di flessione. L'esaminatore applica una forza in valgo (medializzante) sul ginocchio.",
    positive: "Apertura mediale dell'articolazione = lesione del LCM. A 0° suggerisce anche LCA/LCP. A 30° è isolata al LCM.",
    sensitivity: "86%", specificity: "Non noto",
  },
  {
    name: "Varo stress test",
    district: "knee",
    purpose: "Valuta integrità del legamento collaterale laterale (LCL).",
    procedure: "Paziente supino, ginocchio a 0° e poi a 30° di flessione. L'esaminatore applica una forza in varo (lateralizzante).",
    positive: "Apertura laterale dell'articolazione = lesione del LCL.",
    sensitivity: "25%", specificity: "Non noto",
  },

  // ═════ GINOCCHIO — FEMORO-ROTULEA ═══════════════════════════════
  {
    name: "Patellar Grind (Clarke)",
    district: "knee",
    purpose: "Identifica condromalacia rotulea o sindrome femoro-rotulea.",
    procedure: "Paziente supino, ginocchio esteso. L'esaminatore comprime la rotula contro la troclea e chiede al paziente di contrarre il quadricipite.",
    positive: "Dolore o crepitio retropatellare = condromalacia rotulea / PFPS.",
    sensitivity: "49%", specificity: "75%",
    aliases: ["Clarke sign"],
  },
  {
    name: "Patellar Apprehension",
    district: "knee",
    purpose: "Identifica instabilità patellare (lussazione/sublussazione rotulea).",
    procedure: "Paziente supino, ginocchio in lieve flessione. L'esaminatore spinge la rotula lateralmente.",
    positive: "Apprehension o contrazione protettiva del quadricipite = instabilità rotulea.",
    sensitivity: "32%", specificity: "86%",
  },
  {
    name: "Patellar Tilt",
    district: "knee",
    purpose: "Valuta retrazione del retinacolo laterale.",
    procedure: "Paziente supino, ginocchio esteso, quadricipite rilassato. L'esaminatore solleva il bordo laterale della rotula.",
    positive: "Incapacità di sollevare oltre l'orizzontale = retrazione del retinacolo laterale.",
  },
  {
    name: "Q-angle",
    district: "knee",
    purpose: "Valuta allineamento rotuleo (aumenta il rischio di PFPS).",
    procedure: "Si misura l'angolo tra una linea dall'EIAS al centro della rotula e una dal centro della rotula alla tuberosità tibiale.",
    positive: "Q-angle >15° (uomo) o >20° (donna) = malallineamento rotuleo (rischio PFPS).",
  },

  // ═════ GINOCCHIO — PES ANSERINO/ITB ═════════════════════════════
  {
    name: "Noble compression test",
    district: "knee",
    purpose: "Identifica sindrome della bandelletta ileo-tibiale (ITB).",
    procedure: "Paziente supino, ginocchio a 90°. L'esaminatore comprime la bandelletta sul condilo femorale laterale durante estensione progressiva del ginocchio.",
    positive: "Dolore a 30° di flessione = sindrome della bandelletta ileo-tibiale.",
  },
  {
    name: "Renne test",
    district: "knee",
    purpose: "Identifica sindrome della bandelletta ileo-tibiale (test in carico).",
    procedure: "Paziente in piedi su una gamba con ginocchio a 30-40° di flessione.",
    positive: "Dolore sul condilo femorale laterale = sindrome della bandelletta.",
  },

  // ═════ CAVIGLIA — LEGAMENTI ═════════════════════════════════════
  {
    name: "Anterior Drawer caviglia",
    district: "ankle",
    purpose: "Identifica lesione del legamento peroneo-astragalico anteriore (PAA).",
    procedure: "Paziente seduto con piede in lieve plantarflessione (20°). L'esaminatore stabilizza la tibia e trae il calcagno in avanti.",
    positive: "Aumentata traslazione anteriore del talo (>3 mm rispetto al lato sano) = lesione del PAA.",
    sensitivity: "74%", specificity: "38%",
  },
  {
    name: "Talar Tilt (Inversion)",
    district: "ankle",
    purpose: "Identifica lesione del legamento peroneo-calcaneare.",
    procedure: "Paziente seduto, piede neutro. L'esaminatore stabilizza la tibia e applica un'inversione forzata al calcagno.",
    positive: "Aumentata inversione rispetto al lato controlaterale = lesione del peroneo-calcaneare.",
    sensitivity: "52%", specificity: "88%",
  },
  {
    name: "Squeeze test",
    district: "ankle",
    purpose: "Identifica lesione della sindesmosi tibio-peroneale (alta caviglia).",
    procedure: "L'esaminatore comprime la fibula contro la tibia a metà gamba.",
    positive: "Dolore in regione della sindesmosi distale = lesione della sindesmosi (alta caviglia).",
    sensitivity: "30%", specificity: "94%", source: "Alonso et al. 1998",
  },
  {
    name: "External Rotation test (Kleiger)",
    district: "ankle",
    purpose: "Identifica lesione della sindesmosi.",
    procedure: "Paziente seduto, ginocchio a 90°, piede neutro. L'esaminatore stabilizza la gamba e ruota esternamente il piede.",
    positive: "Dolore alla sindesmosi distale o all'alto della caviglia = lesione sindesmotica.",
    sensitivity: "20%", specificity: "85%",
    aliases: ["Kleiger test"],
  },
  {
    name: "Thompson",
    district: "ankle",
    purpose: "Identifica rottura completa del tendine d'Achille.",
    procedure: "Paziente prono con piedi fuori dal lettino. L'esaminatore comprime il polpaccio.",
    positive: "Assenza di plantarflessione del piede = rottura completa del tendine d'Achille.",
    sensitivity: "96%", specificity: "93%", source: "Maffulli 1998",
  },
  {
    name: "Matles test",
    district: "ankle",
    purpose: "Identifica rottura del tendine d'Achille (test attivo).",
    procedure: "Paziente prono. Si chiede di flettere il ginocchio a 90°. L'esaminatore osserva la posizione del piede.",
    positive: "Caduta del piede in dorsiflessione (perdita del tono di plantarflessione) = rottura del tendine d'Achille.",
    sensitivity: "88%", specificity: "85%",
  },
  {
    name: "Tinel caviglia (tunnel tarsale)",
    district: "ankle",
    purpose: "Identifica sindrome del tunnel tarsale (compressione del nervo tibiale posteriore).",
    procedure: "L'esaminatore percuote il retinacolo dei flessori dietro il malleolo mediale.",
    positive: "Parestesie nella pianta del piede = sindrome del tunnel tarsale.",
  },
  {
    name: "Mulder click",
    district: "ankle",
    purpose: "Identifica neuroma di Morton (tipicamente terzo spazio intermetatarsale).",
    procedure: "L'esaminatore comprime medio-lateralmente l'avampiede comprimendo gli spazi intermetatarsali.",
    positive: "Click doloroso = neuroma di Morton.",
    sensitivity: "61%", specificity: "100%",
  },
  {
    name: "Windlass test",
    district: "ankle",
    purpose: "Identifica fascite plantare.",
    procedure: "Paziente in piedi o supino. L'esaminatore estende passivamente l'alluce.",
    positive: "Riproduzione del dolore alla fascia plantare = fascite plantare.",
    sensitivity: "32%", specificity: "100%",
  },
  {
    name: "Homans sign",
    district: "ankle",
    purpose: "Screening per trombosi venosa profonda (TVP) — bassa accuratezza, da usare con cautela.",
    procedure: "Paziente supino, ginocchio esteso. L'esaminatore dorsiflette passivamente la caviglia.",
    positive: "Dolore al polpaccio = sospetta TVP. ATTENZIONE: alta percentuale di falsi positivi/negativi, non sostituisce ecocolordoppler.",
    sensitivity: "10-54%", specificity: "39-89%", source: "Urbano 2001 (test storico, accuratezza limitata)",
  },
  {
    name: "Navicular Drop",
    district: "ankle",
    purpose: "Valuta iperpronazione/piede piatto funzionale.",
    procedure: "Si misura la distanza navicolare-suolo in posizione neutra subtalare seduto, poi in posizione di carico in piedi.",
    positive: "Drop >10 mm = iperpronazione/piede piatto.",
  },
  {
    name: "Single Heel Rise",
    district: "ankle",
    purpose: "Valuta funzione del tibiale posteriore.",
    procedure: "Paziente in piedi su una gamba sola. Si chiede di sollevarsi sulla punta del piede (heel rise).",
    positive: "Incapacità di sollevarsi o assenza di inversione del calcagno = disfunzione del tibiale posteriore.",
    sensitivity: "90%", specificity: "Non noto",
  },
];
