// ═══════════════════════════════════════════════════════════════════════
// src/lib/clinical/orthopedicTests/spine.ts
// ═══════════════════════════════════════════════════════════════════════
// Test ortopedici del rachide: cervicale, dorsale, lombare, sacroiliaca, ATM.
// Fonti: Magee 6th ed., Cook & Hegedus 3rd ed., Physiopedia, Physiotutors.
// ═══════════════════════════════════════════════════════════════════════

import type { OrthopedicTest } from "./types";

export const SPINE_TESTS: OrthopedicTest[] = [

  // ═════ RACHIDE CERVICALE ═════════════════════════════════════════
  {
    name: "Spurling",
    district: "cervical",
    purpose: "Valuta radicolopatia cervicale (compressione del foro intervertebrale).",
    procedure: "Paziente seduto. L'esaminatore estende, lateralmente flette e ruota il capo dal lato sintomatico, poi applica una compressione assiale verso il basso di circa 7kg.",
    positive: "Riproduzione del dolore radicolare nell'arto superiore = compressione del foro intervertebrale.",
    sensitivity: "30-50%", specificity: "74-93%", source: "Tong et al. 2002; Wainner et al. 2003",
  },
  {
    name: "Distraction test cervicale",
    district: "cervical",
    purpose: "Conferma radicolopatia cervicale per riduzione della compressione foraminale.",
    procedure: "Paziente supino o seduto. L'esaminatore afferra mento e occipite, applica trazione assiale di circa 14kg.",
    positive: "Diminuzione del dolore radicolare = sollievo dalla compressione del foro intervertebrale.",
    sensitivity: "40-44%", specificity: "90-97%", source: "Wainner et al. 2003",
  },
  {
    name: "Upper Limb Tension Test 1 (ULTT-1, mediano)",
    district: "cervical",
    purpose: "Valuta tensione neurale del nervo mediano e radici C5-C7.",
    procedure: "Paziente supino. Depressione scapolare, abduzione 110°, supinazione, estensione polso/dita, rotazione esterna spalla, estensione gomito, lateroflessione cervicale controlaterale.",
    positive: "Riproduzione dei sintomi del paziente = neuropatia/tensione del nervo mediano o radici cervicali.",
    sensitivity: "97%", specificity: "22%", source: "Wainner et al. 2003",
    aliases: ["ULTT", "Test di tensione mediano"],
  },
  {
    name: "Adson",
    district: "vascular",
    purpose: "Screening per Sindrome dello Stretto Toracico (TOS) - compressione vascolare.",
    procedure: "Paziente seduto, braccio del lato esaminato esteso e leggermente abdotto. Si palpa il polso radiale. Il paziente ruota il capo dal lato esaminato, lo estende e inspira profondamente trattenendo il respiro.",
    positive: "Diminuzione o scomparsa del polso radiale = compressione vascolare (sindrome dello stretto toracico).",
    sensitivity: "79%", specificity: "76%", source: "Gillard et al. 2001",
    aliases: ["Adson's test", "Adson maneuver"],
  },
  {
    name: "Roos (EAST)",
    district: "vascular",
    purpose: "Screening per Sindrome dello Stretto Toracico (TOS) neurogena/vascolare.",
    procedure: "Paziente seduto. Braccia abdotte a 90°, rotazione esterna, gomiti flessi a 90°. Apertura e chiusura delle mani per 3 minuti.",
    positive: "Incapacità a completare i 3 minuti, riproduzione dei sintomi, pallore o intorpidimento = TOS.",
    sensitivity: "84%", specificity: "30-100%", source: "Gillard et al. 2001",
    aliases: ["Elevated Arm Stress Test", "EAST"],
  },
  {
    name: "Wright",
    district: "vascular",
    purpose: "Screening per compressione vascolare ascellare/succlavia (TOS).",
    procedure: "Paziente seduto. L'esaminatore palpa il polso radiale e abduce passivamente la spalla a 90° con rotazione esterna massimale. Si chiede di trattenere il respiro.",
    positive: "Diminuzione o scomparsa del polso = compressione della succlavia/ascellare sotto il piccolo pettorale.",
    sensitivity: "70-90%", specificity: "29-53%", source: "Plewa & Delinger 1998",
  },
  {
    name: "Test arteria vertebrale (VBI)",
    district: "cervical",
    purpose: "Screening per insufficienza vertebro-basilare prima di manipolazioni cervicali.",
    procedure: "Paziente supino. L'esaminatore estende il capo, lo ruota dal lato opposto e mantiene la posizione 30 secondi. Si ripete dall'altro lato.",
    positive: "Vertigini, nistagmo, nausea, sincope, disartria, drop attack = insufficienza vertebro-basilare. CONTROINDICAZIONE alle manipolazioni cervicali.",
    sensitivity: "Bassa", specificity: "Variabile", source: "Hutting et al. 2013 (test di screening, non diagnostico)",
    aliases: ["VBI test", "DeKleyn"],
  },
  {
    name: "Sharp-Purser",
    district: "cervical",
    purpose: "Valuta instabilità del legamento trasverso (C1-C2), tipica in artrite reumatoide.",
    procedure: "Paziente seduto, capo lievemente flesso. L'esaminatore stabilizza C2 con il pollice, posiziona l'altra mano sulla fronte e applica una pressione posteriore.",
    positive: "Scivolamento del capo all'indietro (>3-4 mm) = instabilità atlanto-assiale.",
    sensitivity: "69%", specificity: "96%", source: "Uitvlugt & Indenbaum 1988",
  },
  {
    name: "Alar Ligament test",
    district: "cervical",
    purpose: "Valuta integrità dei legamenti alari (stabilità C1-C2 in rotazione/laterale).",
    procedure: "Paziente supino. L'esaminatore stabilizza C2 con presa laterale, poi inclina lateralmente il capo.",
    positive: "Assenza di movimento di C2 durante la lateroflessione = lassità/rottura legamento alare.",
    source: "Kaale et al. 2008",
  },
  {
    name: "Hautant",
    district: "cervical",
    purpose: "Differenzia vertigine vestibolare da vertigine cervicogenica/vascolare.",
    procedure: "Paziente seduto, braccia tese in avanti, occhi chiusi. Si chiede di mantenere la posizione, poi di estendere e ruotare il capo per 30 secondi.",
    positive: "Deviazione laterale delle braccia con rotazione/estensione cervicale = compromissione vascolare o cervicogenica.",
  },
  {
    name: "Bakody (Shoulder Abduction Test)",
    district: "cervical",
    purpose: "Valuta sollievo da radicolopatia C4-C6 in posizione di scarico.",
    procedure: "Paziente seduto. Il paziente abduce attivamente il braccio sintomatico e appoggia la mano sopra la testa.",
    positive: "Diminuzione del dolore radicolare in questa posizione = ernia cervicale o compressione radicolare.",
    sensitivity: "17-78%", specificity: "75-92%", source: "Wainner et al. 2003",
    aliases: ["Shoulder Abduction Relief Sign"],
  },
  {
    name: "Valsalva cervicale",
    district: "cervical",
    purpose: "Identifica lesione occupante spazio nel canale cervicale.",
    procedure: "Manovra di Valsalva (espirazione forzata a glottide chiusa per ~3 secondi).",
    positive: "Aumento del dolore radicolare o riproduzione dei sintomi = lesione occupante spazio (ernia, tumore).",
    sensitivity: "22%", specificity: "94%", source: "Viikari-Juntura et al. 1989",
  },

  // ═════ ATM ═════════════════════════════════════════════════════
  {
    name: "Apertura attiva ATM",
    district: "tmj",
    purpose: "Valuta range di motion e simmetria dell'apertura mandibolare.",
    procedure: "Il paziente apre la bocca al massimo. Si misura la distanza interincisiva (normale 40-50 mm).",
    positive: "<35 mm = limitazione. Deviazione laterale durante apertura = disfunzione monolaterale.",
  },
  {
    name: "Compressione ATM",
    district: "tmj",
    purpose: "Identifica patologia intra-articolare dell'ATM (capsulite, artrite).",
    procedure: "Paziente con bocca leggermente aperta. L'esaminatore applica compressione assiale dal mento verso l'alto.",
    positive: "Dolore in regione preauricolare = patologia intra-articolare.",
  },
  {
    name: "Distraction ATM",
    district: "tmj",
    purpose: "Valuta riproduzione del dolore con trazione del condilo mandibolare.",
    procedure: "L'esaminatore inserisce il pollice sui molari inferiori e applica trazione caudale.",
    positive: "Dolore in regione articolare = capsulite o lesione legamentosa ATM.",
  },
  {
    name: "Crepitio/Click ATM",
    district: "tmj",
    purpose: "Identifica dislocazione del disco articolare ATM.",
    procedure: "L'esaminatore palpa le ATM bilateralmente mentre il paziente apre e chiude lentamente la bocca.",
    positive: "Click in apertura/chiusura = dislocazione discale con riduzione. Crepitio = artrosi.",
  },

  // ═════ RACHIDE DORSALE ═════════════════════════════════════════
  {
    name: "Slump test toracico",
    district: "thoracic",
    purpose: "Valuta tensione neurale meningea con coinvolgimento dorsale.",
    procedure: "Paziente seduto. Flessione completa del rachide (slump), flessione cervicale, estensione progressiva del ginocchio.",
    positive: "Riproduzione dei sintomi dorsali con la flessione cervicale, sollievo con estensione del rachide = irritazione neuro-meningea.",
  },
  {
    name: "Adam's Forward Bend",
    district: "thoracic",
    purpose: "Screening per scoliosi strutturale (gibbo costale).",
    procedure: "Paziente in piedi. Si chiede di piegarsi in avanti con braccia rilassate. L'esaminatore osserva da dietro.",
    positive: "Gibbo costale asimmetrico = scoliosi strutturale (rotazione vertebrale).",
    sensitivity: "84%", specificity: "93%", source: "Bunnell 1984",
  },
  {
    name: "Sternal compression",
    district: "thoracic",
    purpose: "Valuta integrità delle costole / fratture costali.",
    procedure: "Paziente supino. L'esaminatore applica compressione antero-posteriore sullo sterno.",
    positive: "Dolore localizzato in una costa = sospetta frattura costale.",
  },
  {
    name: "Rib spring test",
    district: "thoracic",
    purpose: "Identifica disfunzioni costali individuali.",
    procedure: "Paziente prono. L'esaminatore applica una pressione 'a molla' verso il basso su ogni costa.",
    positive: "Resistenza o dolore in una singola costa = disfunzione costale localizzata.",
  },

  // ═════ RACHIDE LOMBARE ═════════════════════════════════════════
  {
    name: "Lasègue (SLR)",
    district: "lumbar",
    purpose: "Valuta irritazione radicolare lombo-sacrale (L4-S1), tipica nell'ernia discale.",
    procedure: "Paziente supino. L'esaminatore solleva l'arto inferiore esteso (ginocchio in estensione) flettendo l'anca, fino a comparsa di dolore.",
    positive: "Dolore radicolare tra 30°-70° di flessione d'anca = irritazione delle radici L4-S1. Dolore <30° = neoplasia/infiammazione; >70° = origine articolare.",
    sensitivity: "91%", specificity: "26%", source: "Deville et al. 2000 (meta-analisi)",
    aliases: ["SLR", "Straight Leg Raise"],
  },
  {
    name: "Bragard",
    district: "lumbar",
    purpose: "Conferma del Lasègue, sensibilizza la dorsiflessione plantare.",
    procedure: "Estensione del SLR: arrivato alla posizione di dolore, si abbassa l'arto di 5-10° e si dorsiflette la caviglia.",
    positive: "Riproduzione del dolore radicolare con la dorsiflessione = irritazione radicolare lombare.",
  },
  {
    name: "SLR contralaterale (Crossed SLR)",
    district: "lumbar",
    purpose: "Identifica ernia discale mediale di grande dimensione (alta specificità).",
    procedure: "Come Lasègue ma sull'arto sano (contro-laterale).",
    positive: "Riproduzione del dolore radicolare nell'arto sintomatico = ernia mediale.",
    sensitivity: "29%", specificity: "88%", source: "Deville et al. 2000",
    aliases: ["Crossed SLR", "Well Leg Raise"],
  },
  {
    name: "Kemp (Quadrant lombare)",
    district: "lumbar",
    purpose: "Identifica patologia faccetaria o radicolare lombare.",
    procedure: "Paziente in piedi o seduto. Estensione lombare combinata con rotazione e lateroflessione dal lato sintomatico.",
    positive: "Dolore radicolare = compressione radicolare. Dolore locale = sindrome faccetaria.",
    aliases: ["Quadrant test"],
  },
  {
    name: "Slump test",
    district: "lumbar",
    purpose: "Valuta tensione neurale del tratto lombo-sacrale (più sensibile del SLR).",
    procedure: "Paziente seduto. Flessione del rachide, poi flessione cervicale, estensione progressiva del ginocchio, dorsiflessione della caviglia.",
    positive: "Riproduzione dei sintomi che diminuiscono con l'estensione cervicale = irritazione neuro-meningea.",
    sensitivity: "84%", specificity: "83%", source: "Majlesi et al. 2008",
  },
  {
    name: "Prone Knee Bending (Femoral SLR)",
    district: "lumbar",
    purpose: "Valuta irritazione delle radici L2-L4 o stiramento del nervo femorale.",
    procedure: "Paziente prono. L'esaminatore flette passivamente il ginocchio portando il tallone verso il gluteo.",
    positive: "Dolore in regione anteriore della coscia o lombare = irritazione delle radici L2-L4.",
    aliases: ["Femoral SLR", "Ely's test"],
  },
  {
    name: "Valsalva lombare",
    district: "lumbar",
    purpose: "Identifica lesione occupante spazio nel canale lombare.",
    procedure: "Il paziente esegue una manovra di Valsalva (espirazione forzata a glottide chiusa).",
    positive: "Aumento del dolore lombare o radicolare = aumentata pressione intratecale (ernia, tumore).",
    sensitivity: "22%", specificity: "94%",
  },
  {
    name: "Schober modificato",
    district: "lumbar",
    purpose: "Misura la flessione del rachide lombare (utile in spondiliti).",
    procedure: "Paziente in piedi. Si marca un punto a livello L5-S1 e uno 10 cm sopra. Si chiede flessione anteriore massima e si rimisura.",
    positive: "Incremento <5 cm = riduzione della mobilità lombare (spondilite anchilosante, rigidità).",
    sensitivity: "30%", specificity: "98%", source: "Macrae & Wright 1969",
  },
  {
    name: "Hoover test",
    district: "lumbar",
    purpose: "Identifica simulazione/paralisi non organica nell'arto inferiore.",
    procedure: "Paziente supino. L'esaminatore pone le mani sotto i talloni. Si chiede di sollevare l'arto sintomatico.",
    positive: "Assenza di pressione del tallone controlaterale durante lo sforzo = sospetto di simulazione o paralisi non organica.",
  },
  {
    name: "Stork test (Single Leg Stance)",
    district: "lumbar",
    purpose: "Identifica spondilolisi/spondilolistesi o disfunzione faccetaria.",
    procedure: "Paziente in piedi su una gamba sola, estende il rachide.",
    positive: "Dolore lombare omolaterale = spondilolisi o disfunzione faccetaria sullo stesso lato.",
    sensitivity: "55%", specificity: "68%", source: "Masci et al. 2006",
    aliases: ["One Leg Hyperextension Test"],
  },
  {
    name: "Prone Instability Test",
    district: "lumbar",
    purpose: "Identifica instabilità segmentale lombare.",
    procedure: "Paziente prono con tronco sul lettino e gambe a terra. L'esaminatore applica pressione antero-posteriore sui processi spinosi. Poi il paziente solleva le gambe e si ripete.",
    positive: "Dolore presente con gambe a terra ma assente con gambe sollevate = instabilità segmentale.",
    sensitivity: "61%", specificity: "57%", source: "Hicks et al. 2003",
  },
  {
    name: "Centralizzazione (McKenzie)",
    district: "lumbar",
    purpose: "Identifica origine discale del dolore e direzione preferenziale di movimento.",
    procedure: "Movimenti ripetuti in direzioni specifiche (estensione, flessione, lateroflessione) per 10 ripetizioni.",
    positive: "Centralizzazione del dolore (dalla periferia verso il centro) durante una direzione = derangement discale risolvibile in quella direzione.",
    sensitivity: "40-92%", specificity: "84-100%", source: "Werneke et al. 2011",
  },
  {
    name: "Test di Mennell",
    district: "lumbar",
    purpose: "Valuta dolore di origine sacroiliaca o lombare bassa.",
    procedure: "Paziente in decubito laterale. L'esaminatore stabilizza il bacino e iperestende l'anca superiore.",
    positive: "Dolore alla sacroiliaca = disfunzione SI. Dolore lombare = ipertono iliopsoas/lesione faccetaria.",
  },
  {
    name: "Beevor",
    district: "lumbar",
    purpose: "Valuta integrità neurologica T6-T12 e simmetria dei retti addominali.",
    procedure: "Paziente supino. Si chiede di eseguire un mezzo sit-up. L'esaminatore osserva l'ombelico.",
    positive: "Deviazione dell'ombelico verso un lato = denervazione/debolezza dei muscoli addominali da un lato.",
  },

  // ═════ SACROILIACA ═════════════════════════════════════════════
  {
    name: "FABER (Patrick)",
    district: "sacroiliac",
    purpose: "Test multi-scopo: valuta sacroiliaca, anca intra-articolare, ileopsoas.",
    procedure: "Paziente supino. Flessione, abduzione ed extra-rotazione dell'anca (posizione 'numero 4'). L'esaminatore applica una pressione verso il basso sul ginocchio flesso e sull'EIAS controlaterale.",
    positive: "Dolore inguinale = patologia intra-articolare d'anca. Dolore posteriore/SI = disfunzione sacroiliaca.",
    sensitivity: "57-77%", specificity: "100%", source: "Laslett et al. 2005 (per SI)",
    aliases: ["Patrick test", "Figure-4 test"],
  },
  {
    name: "Gaenslen",
    district: "sacroiliac",
    purpose: "Stress provocativo della sacroiliaca tramite iperestensione d'anca.",
    procedure: "Paziente supino al bordo del lettino. Un arto pende fuori in iperestensione, l'altro è flesso al petto. L'esaminatore applica overpressure.",
    positive: "Dolore alla sacroiliaca omolaterale all'arto in estensione = disfunzione SI.",
    sensitivity: "53%", specificity: "71%", source: "Laslett et al. 2005",
  },
  {
    name: "Compression sacroiliaca",
    district: "sacroiliac",
    purpose: "Stress provocativo SI in compressione mediale.",
    procedure: "Paziente in decubito laterale. L'esaminatore applica una pressione verso il basso sulla cresta iliaca superiore.",
    positive: "Dolore alla sacroiliaca sottostante = disfunzione SI.",
    sensitivity: "69%", specificity: "69%", source: "Laslett et al. 2005",
  },
  {
    name: "Distraction sacroiliaca",
    district: "sacroiliac",
    purpose: "Stress provocativo SI in apertura.",
    procedure: "Paziente supino. L'esaminatore applica pressione verso il basso e in fuori sulle due EIAS contemporaneamente.",
    positive: "Dolore alla sacroiliaca = disfunzione SI (parte anteriore).",
    sensitivity: "60%", specificity: "81%", source: "Laslett et al. 2005",
  },
  {
    name: "Thigh Thrust (P4)",
    district: "sacroiliac",
    purpose: "Stress provocativo SI tramite forza assiale femorale.",
    procedure: "Paziente supino, anca flessa a 90°. L'esaminatore applica una forza assiale lungo il femore verso il basso (P4 = posterior pelvic pain provocation).",
    positive: "Dolore alla sacroiliaca = disfunzione SI. Test ad alta sensibilità.",
    sensitivity: "88%", specificity: "69%", source: "Laslett et al. 2005",
  },
  {
    name: "Sacral Thrust",
    district: "sacroiliac",
    purpose: "Stress provocativo del sacro.",
    procedure: "Paziente prono. L'esaminatore applica pressione antero-posteriore sull'apice del sacro.",
    positive: "Dolore alla sacroiliaca = disfunzione SI.",
    sensitivity: "53%", specificity: "75%", source: "Laslett et al. 2005",
  },
  {
    name: "Cluster of Laslett",
    district: "sacroiliac",
    purpose: "Combinazione di 3-5 test SI per aumentare la diagnostica.",
    procedure: "Si eseguono Distraction, Thigh Thrust, Compression, Sacral Thrust, Gaenslen. Se ≥3 positivi su 5, il cluster è positivo.",
    positive: "≥3 test su 5 positivi = elevata probabilità di disfunzione sacroiliaca.",
    sensitivity: "91%", specificity: "78%", source: "Laslett et al. 2005",
    aliases: ["Laslett cluster", "Pain provocation cluster"],
  },
  {
    name: "Gillet (Stork test)",
    district: "sacroiliac",
    purpose: "Valuta il movimento posteriore della SIPS durante la flessione dell'anca.",
    procedure: "Paziente in piedi. L'esaminatore palpa la SIPS e S2. Si chiede di portare il ginocchio dello stesso lato al petto.",
    positive: "Mancato movimento posteriore della SIPS (rispetto a S2) = disfunzione di mobilità SI.",
    sensitivity: "8-43%", specificity: "68-93%", source: "Riddle & Freburger 2002 (bassa affidabilità)",
    aliases: ["Stork SI test"],
  },
  {
    name: "Standing Flexion",
    district: "sacroiliac",
    purpose: "Valuta asimmetria del movimento delle SIPS in flessione del tronco.",
    procedure: "Paziente in piedi. L'esaminatore palpa le SIPS. Si chiede flessione anteriore.",
    positive: "Movimento asimmetrico delle SIPS (una sale più dell'altra) = sospetta disfunzione SI.",
    source: "Bassa affidabilità in letteratura (Riddle & Freburger 2002)",
  },
];
