// ═══════════════════════════════════════════════════════════════════════
// src/lib/clinical/orthopedicTests/upperLimb.ts
// ═══════════════════════════════════════════════════════════════════════
// Test ortopedici arto superiore: spalla, gomito, polso/mano.
// Fonti: Magee 6th ed., Cook & Hegedus, Physiopedia, Hegedus systematic review.
// ═══════════════════════════════════════════════════════════════════════

import type { OrthopedicTest } from "./types";

export const UPPER_LIMB_TESTS: OrthopedicTest[] = [

  // ═════ SPALLA — IMPINGEMENT ═════════════════════════════════════
  {
    name: "Hawkins-Kennedy",
    district: "shoulder",
    purpose: "Identifica conflitto sub-acromiale (impingement del sovraspinato).",
    procedure: "Spalla a 90° di flessione anteriore, gomito a 90°. L'esaminatore stabilizza la scapola e ruota internamente la spalla con forza.",
    positive: "Dolore antero-laterale della spalla = conflitto sub-acromiale.",
    sensitivity: "74-92%", specificity: "26-50%", source: "Hegedus et al. 2012",
  },
  {
    name: "Neer",
    district: "shoulder",
    purpose: "Identifica conflitto sub-acromiale.",
    procedure: "Paziente seduto. L'esaminatore stabilizza la scapola con una mano e porta passivamente l'arto in flessione massimale con rotazione interna.",
    positive: "Dolore antero-laterale = conflitto sub-acromiale.",
    sensitivity: "72-88%", specificity: "30-49%", source: "Hegedus et al. 2012",
  },
  {
    name: "Painful Arc",
    district: "shoulder",
    purpose: "Identifica conflitto sub-acromiale tramite range di motion attivo.",
    procedure: "Il paziente abduce attivamente la spalla nel piano scapolare.",
    positive: "Dolore tra 60°-120° di abduzione, assente sotto e sopra = impingement sub-acromiale.",
    sensitivity: "73%", specificity: "81%", source: "Park et al. 2005",
  },

  // ═════ SPALLA — CUFFIA ROTATORI ═════════════════════════════════
  {
    name: "Jobe (Empty Can)",
    district: "shoulder",
    purpose: "Identifica lesione o tendinopatia del sovraspinato.",
    procedure: "Arto a 90° di abduzione, 30° di flessione orizzontale (piano scapolare), pollice verso il basso ('lattina vuota'). L'esaminatore resiste l'abduzione.",
    positive: "Dolore o debolezza nel sovraspinato.",
    sensitivity: "44-79%", specificity: "53-90%", source: "Hegedus et al. 2012",
    aliases: ["Empty Can"],
  },
  {
    name: "Full Can",
    district: "shoulder",
    purpose: "Valuta sovraspinato con minore impingement (variante più sensibile).",
    procedure: "Arto a 90° di abduzione, 30° di flessione orizzontale, pollice verso l'alto. Si resiste l'abduzione.",
    positive: "Dolore o debolezza = lesione/tendinopatia del sovraspinato.",
    sensitivity: "75%", specificity: "74%", source: "Itoi et al. 1999",
  },
  {
    name: "Drop Arm",
    district: "shoulder",
    purpose: "Identifica lesioni complete del sovraspinato.",
    procedure: "L'esaminatore porta passivamente l'arto a 90° di abduzione, poi chiede al paziente di abbassarlo lentamente.",
    positive: "Caduta dell'arto o incapacità di controllare il movimento = lesione completa del sovraspinato.",
    sensitivity: "8-35%", specificity: "97-100%", source: "Hegedus et al. 2012",
  },
  {
    name: "Lift-off (Gerber)",
    district: "shoulder",
    purpose: "Identifica lesione del sottoscapolare.",
    procedure: "Paziente in piedi. Dorso della mano contro la regione lombare. Si chiede di staccare la mano dalla schiena.",
    positive: "Impossibilità a staccare la mano = lesione del sottoscapolare.",
    sensitivity: "27-62%", specificity: "60-100%", source: "Hegedus et al. 2012",
  },
  {
    name: "Belly Press",
    district: "shoulder",
    purpose: "Identifica lesione del sottoscapolare (variante più tollerata del Lift-off).",
    procedure: "Paziente in piedi. Palmo della mano sull'addome, gomito anteriore al tronco. Si chiede di premere sull'addome senza arretrare il gomito.",
    positive: "Gomito che cade indietro o impossibilità a mantenere la pressione = lesione del sottoscapolare.",
    sensitivity: "40-90%", specificity: "85-98%", source: "Tokish et al. 2003",
    aliases: ["Napoleon test"],
  },
  {
    name: "External Rotation Lag Sign",
    district: "shoulder",
    purpose: "Identifica lesione del sovraspinato/infraspinato.",
    procedure: "Paziente seduto. L'esaminatore porta passivamente la spalla in 20° di abduzione, gomito a 90°, massima rotazione esterna. Si chiede di mantenere la posizione.",
    positive: "Caduta del braccio in rotazione interna (lag >5°) = lesione infraspinato/sovraspinato.",
    sensitivity: "70%", specificity: "55%", source: "Hertel et al. 1996",
    aliases: ["ERLS"],
  },
  {
    name: "Hornblower's Sign",
    district: "shoulder",
    purpose: "Identifica lesione del piccolo rotondo.",
    procedure: "Spalla a 90° di abduzione e 90° di rotazione esterna. Si chiede di portare la mano alla bocca.",
    positive: "Sollevamento del gomito sopra la mano per compensare = lesione del piccolo rotondo.",
    sensitivity: "100%", specificity: "93%", source: "Walch et al. 1998",
  },
  {
    name: "Bear Hug",
    district: "shoulder",
    purpose: "Identifica lesione del sottoscapolare alto.",
    procedure: "Paziente con mano appoggiata sulla spalla controlaterale, gomito anteriore. Si chiede di mantenere la posizione contro resistenza in rotazione esterna.",
    positive: "Incapacità di mantenere la mano sulla spalla = lesione del sottoscapolare.",
    sensitivity: "60%", specificity: "92%", source: "Barth et al. 2006",
  },

  // ═════ SPALLA — BICIPITE & SLAP ═════════════════════════════════
  {
    name: "Speed",
    district: "shoulder",
    purpose: "Identifica tendinopatia del capo lungo del bicipite o lesione SLAP.",
    procedure: "Arto in flessione a 90°, gomito esteso, palmo verso l'alto (supinato). L'esaminatore resiste la flessione anteriore della spalla.",
    positive: "Dolore al solco bicipitale = tendinopatia del capo lungo del bicipite.",
    sensitivity: "32-69%", specificity: "75-89%", source: "Hegedus et al. 2012",
  },
  {
    name: "Yergason",
    district: "shoulder",
    purpose: "Identifica tendinopatia o instabilità del capo lungo del bicipite.",
    procedure: "Gomito flesso a 90° addotto al fianco, avambraccio pronato. L'esaminatore resiste la supinazione e l'extra-rotazione.",
    positive: "Dolore al solco bicipitale o scatto del tendine = tendinopatia/sublussazione del bicipite.",
    sensitivity: "32-43%", specificity: "79-93%", source: "Hegedus et al. 2012",
  },
  {
    name: "O'Brien (Active Compression)",
    district: "shoulder",
    purpose: "Identifica lesione SLAP (Superior Labrum Anterior to Posterior).",
    procedure: "Spalla a 90° di flessione, 10° di adduzione, gomito esteso, pollice verso il basso. Si resiste la flessione, poi si ripete con palmo supinato.",
    positive: "Dolore profondo con pollice in basso che diminuisce con palmo in alto = lesione SLAP.",
    sensitivity: "47-78%", specificity: "11-99%", source: "Cook et al. 2012",
  },
  {
    name: "Crank test",
    district: "shoulder",
    purpose: "Identifica lesione del labbro gleno-omerale.",
    procedure: "Spalla a 160° di flessione. L'esaminatore comprime assialmente lungo l'omero e ruota internamente/esternamente la spalla.",
    positive: "Dolore o click = lesione labbrale gleno-omerale.",
    sensitivity: "58%", specificity: "72%", source: "Hegedus et al. 2012",
  },

  // ═════ SPALLA — INSTABILITÀ ═════════════════════════════════════
  {
    name: "Apprehension test (spalla)",
    district: "shoulder",
    purpose: "Identifica instabilità antero-inferiore di spalla.",
    procedure: "Paziente supino. Spalla a 90° di abduzione e 90° di rotazione esterna. L'esaminatore aumenta passivamente la rotazione esterna.",
    positive: "Sensazione di sublussazione imminente (apprehension), NON solo dolore = instabilità antero-inferiore.",
    sensitivity: "53%", specificity: "99%", source: "Lo et al. 2004",
  },
  {
    name: "Relocation test",
    district: "shoulder",
    purpose: "Conferma instabilità antero-inferiore dopo Apprehension positivo.",
    procedure: "Subito dopo Apprehension positivo, l'esaminatore applica una pressione posteriore sulla testa omerale.",
    positive: "Scomparsa della sensazione di apprehension con la riduzione posteriore = instabilità antero-inferiore.",
    sensitivity: "64%", specificity: "90%", source: "Lo et al. 2004",
    aliases: ["Jobe Relocation"],
  },
  {
    name: "Surprise test (Release test)",
    district: "shoulder",
    purpose: "Conferma instabilità anteriore in maniera definitiva.",
    procedure: "Dopo Apprehension/Relocation, l'esaminatore rilascia improvvisamente la pressione posteriore.",
    positive: "Ricomparsa improvvisa dell'apprehension = instabilità antero-inferiore confermata.",
    sensitivity: "64%", specificity: "99%", source: "Lo et al. 2004",
  },
  {
    name: "Sulcus sign",
    district: "shoulder",
    purpose: "Identifica instabilità inferiore della spalla.",
    procedure: "Paziente seduto, arto rilassato lungo il fianco. L'esaminatore applica trazione inferiore al gomito.",
    positive: "Comparsa di una depressione sotto l'acromion >1 cm = lassità capsulare inferiore.",
    sensitivity: "28%", specificity: "97%", source: "Tzannes et al. 2004",
  },
  {
    name: "Load and Shift",
    district: "shoulder",
    purpose: "Valuta lassità anteriore/posteriore della spalla.",
    procedure: "Paziente seduto. L'esaminatore stabilizza la scapola e applica forze antero-posteriori sulla testa omerale.",
    positive: "Traslazione anteriore >50% = lassità anteriore. Posteriore >50% = lassità posteriore.",
  },
  {
    name: "Posterior Apprehension",
    district: "shoulder",
    purpose: "Identifica instabilità posteriore della spalla.",
    procedure: "Paziente supino. Spalla a 90° di flessione e adduzione orizzontale. L'esaminatore applica una forza posteriore lungo l'omero.",
    positive: "Apprehension o dolore posteriore = instabilità posteriore.",
    sensitivity: "20-40%", specificity: "85-95%",
  },

  // ═════ SPALLA — ACROMION-CLAVEARE ═══════════════════════════════
  {
    name: "Cross-body adduction (Scarf)",
    district: "shoulder",
    purpose: "Identifica patologia dell'articolazione acromion-claveare.",
    procedure: "Paziente seduto. L'esaminatore porta passivamente l'arto in adduzione orizzontale, mano verso la spalla controlaterale.",
    positive: "Dolore all'articolazione acromion-claveare = patologia AC.",
    sensitivity: "77%", specificity: "79%", source: "Chronopoulos et al. 2004",
    aliases: ["Scarf test"],
  },
  {
    name: "Paxinos",
    district: "shoulder",
    purpose: "Identifica patologia acromion-claveare.",
    procedure: "L'esaminatore applica pressione antero-superiore sul processo acromiale e infero-anteriore sulla clavicola.",
    positive: "Dolore all'AC = patologia acromion-claveare.",
    sensitivity: "79%", specificity: "50%", source: "Walton et al. 2004",
  },
  {
    name: "AC Resisted Extension",
    district: "shoulder",
    purpose: "Identifica patologia AC con resistenza attiva.",
    procedure: "Spalla a 90° di flessione e adduzione, gomito flesso a 90°. Si resiste l'estensione attiva orizzontale.",
    positive: "Dolore all'AC = patologia acromion-claveare.",
    sensitivity: "72%", specificity: "85%", source: "Chronopoulos et al. 2004",
  },

  // ═════ GOMITO ═══════════════════════════════════════════════════
  {
    name: "Cozen",
    district: "elbow",
    purpose: "Identifica epicondilite laterale ('gomito del tennista').",
    procedure: "Gomito esteso, avambraccio pronato, pugno chiuso. L'esaminatore resiste l'estensione del polso.",
    positive: "Dolore all'epicondilo laterale = epicondilite laterale.",
    sensitivity: "84%", specificity: "Variabile",
  },
  {
    name: "Mill",
    district: "elbow",
    purpose: "Identifica epicondilite laterale (test passivo).",
    procedure: "Gomito esteso. L'esaminatore palpa l'epicondilo laterale e flette passivamente il polso con avambraccio pronato.",
    positive: "Dolore all'epicondilo laterale = epicondilite laterale.",
  },
  {
    name: "Maudsley",
    district: "elbow",
    purpose: "Identifica epicondilite laterale (resistenza dito medio).",
    procedure: "Gomito esteso. Si resiste l'estensione del dito medio del paziente.",
    positive: "Dolore all'epicondilo laterale = epicondilite laterale (stress sull'estensore radiale breve del carpo).",
  },
  {
    name: "Golfer's elbow test (Polk)",
    district: "elbow",
    purpose: "Identifica epitrocleite (epicondilite mediale, 'gomito del golfista').",
    procedure: "Gomito esteso, avambraccio supinato. L'esaminatore estende passivamente il polso del paziente.",
    positive: "Dolore all'epicondilo mediale (epitroclea) = epitrocleite.",
  },
  {
    name: "Tinel gomito (cubital)",
    district: "elbow",
    purpose: "Identifica sindrome del tunnel cubitale (nervo ulnare al gomito).",
    procedure: "L'esaminatore percuote il tunnel cubitale tra epicondilo mediale e olecrano.",
    positive: "Parestesie nel territorio del nervo ulnare (4°-5° dito) = sindrome del tunnel cubitale.",
    sensitivity: "70%", specificity: "98%", source: "Beekman et al. 2004",
  },
  {
    name: "Elbow Flexion Test (Wadsworth)",
    district: "elbow",
    purpose: "Identifica sindrome del tunnel cubitale.",
    procedure: "Paziente mantiene il gomito in massima flessione per 30-60 secondi con polso esteso.",
    positive: "Parestesie nel territorio del nervo ulnare = sindrome del tunnel cubitale.",
    sensitivity: "75%", specificity: "99%", source: "Cheng et al. 2008",
  },
  {
    name: "Varus stress (gomito)",
    district: "elbow",
    purpose: "Valuta integrità del legamento collaterale laterale del gomito.",
    procedure: "Gomito a 20-30° di flessione. L'esaminatore stabilizza l'omero e applica una forza in varo all'avambraccio.",
    positive: "Apertura laterale o dolore = lesione del legamento collaterale laterale del gomito.",
  },
  {
    name: "Valgus stress (gomito)",
    district: "elbow",
    purpose: "Valuta integrità del legamento collaterale mediale del gomito (tipico nei lanciatori).",
    procedure: "Gomito a 20-30° di flessione. L'esaminatore stabilizza l'omero e applica una forza in valgo all'avambraccio.",
    positive: "Apertura mediale o dolore al collaterale mediale = lesione del LCM del gomito.",
    sensitivity: "65%", specificity: "50%",
  },
  {
    name: "Moving Valgus Stress",
    district: "elbow",
    purpose: "Identifica lesione del LCM del gomito durante movimento dinamico.",
    procedure: "Spalla in abduzione e rotazione esterna. Si applica stress in valgo costante mentre si flette/estende il gomito.",
    positive: "Dolore al LCM tra 70°-120° di flessione = lesione del LCM.",
    sensitivity: "100%", specificity: "75%", source: "O'Driscoll et al. 2005",
  },
  {
    name: "Pivot Shift Postero-laterale",
    district: "elbow",
    purpose: "Identifica instabilità postero-laterale del gomito.",
    procedure: "Paziente supino, braccio sopra la testa. L'esaminatore supina l'avambraccio e applica forza in valgo + compressione assiale durante flessione progressiva.",
    positive: "Apprehension o sublussazione del capitello radiale = instabilità postero-laterale.",
    sensitivity: "100%", specificity: "Non noto", source: "O'Driscoll et al. 1991",
  },

  // ═════ POLSO E MANO ═══════════════════════════════════════════
  {
    name: "Phalen",
    district: "wrist",
    purpose: "Identifica sindrome del tunnel carpale (compressione del nervo mediano al polso).",
    procedure: "Il paziente mantiene i polsi in massima flessione (dorsi delle mani uno contro l'altro) per 60 secondi.",
    positive: "Parestesie nel territorio del nervo mediano (pollice, indice, medio, metà radiale anulare) = sindrome del tunnel carpale.",
    sensitivity: "68%", specificity: "73%", source: "MacDermid & Wessel 2004",
  },
  {
    name: "Tinel polso",
    district: "wrist",
    purpose: "Identifica sindrome del tunnel carpale.",
    procedure: "L'esaminatore percuote il tunnel carpale sul versante palmare del polso, sopra il legamento traverso del carpo.",
    positive: "Parestesie nel territorio del nervo mediano = sindrome del tunnel carpale.",
    sensitivity: "50%", specificity: "77%", source: "MacDermid & Wessel 2004",
  },
  {
    name: "Carpal Compression Test (Durkan)",
    district: "wrist",
    purpose: "Identifica sindrome del tunnel carpale (test più sensibile).",
    procedure: "L'esaminatore applica una pressione costante sul tunnel carpale con i pollici per 30 secondi.",
    positive: "Parestesie nel territorio del mediano = sindrome del tunnel carpale.",
    sensitivity: "64-89%", specificity: "30-93%", source: "Durkan 1991",
    aliases: ["Durkan test"],
  },
  {
    name: "Finkelstein",
    district: "wrist",
    purpose: "Identifica tenosinovite di De Quervain (estensore breve e abduttore lungo del pollice).",
    procedure: "Paziente con pollice piegato nel palmo e dita chiuse a pugno sopra. L'esaminatore applica deviazione ulnare al polso.",
    positive: "Dolore all'apice del processo stiloideo radiale = tenosinovite di De Quervain.",
    sensitivity: "81%", specificity: "50%",
  },
  {
    name: "Eichhoff test",
    district: "wrist",
    purpose: "Variante moderna del Finkelstein per De Quervain.",
    procedure: "Pollice flesso nel palmo, pugno chiuso. Deviazione ulnare attiva del polso.",
    positive: "Dolore alla stiloide radiale = De Quervain.",
  },
  {
    name: "Watson scaphoid shift",
    district: "wrist",
    purpose: "Identifica instabilità scafoide-semilunare.",
    procedure: "L'esaminatore stabilizza il polo distale dello scafoide con il pollice durante deviazione del polso da ulnare a radiale.",
    positive: "Click o scatto doloroso = instabilità scafo-semilunare.",
    sensitivity: "69%", specificity: "66%", source: "Easterling & Wolfe 1994",
  },
  {
    name: "Ballottement (Reagan)",
    district: "wrist",
    purpose: "Identifica instabilità luno-piramidale.",
    procedure: "L'esaminatore stabilizza il semilunare con una mano e mobilizza il piramidale con l'altra in direzione antero-posteriore.",
    positive: "Dolore, click o lassità = instabilità luno-piramidale.",
    sensitivity: "64%", specificity: "44%",
  },
  {
    name: "TFCC compression test",
    district: "wrist",
    purpose: "Identifica lesione del complesso fibrocartilagineo triangolare.",
    procedure: "Deviazione ulnare del polso con compressione assiale e rotazione di pronosupinazione.",
    positive: "Dolore ulnare del polso = lesione TFCC.",
    sensitivity: "66%", specificity: "64%",
  },
  {
    name: "Grind test (CMC pollice)",
    district: "wrist",
    purpose: "Identifica rizoartrosi (artrosi trapezio-metacarpale).",
    procedure: "L'esaminatore applica una compressione assiale e una rotazione al primo metacarpo.",
    positive: "Dolore o crepitio all'articolazione carpo-metacarpale del pollice = rizoartrosi.",
    sensitivity: "53-100%", specificity: "30-100%",
  },
  {
    name: "Bunnel-Littler",
    district: "wrist",
    purpose: "Differenzia rigidità della MCP da retrazione degli intrinseci della mano.",
    procedure: "MCP mantenuta in estensione passiva. Si tenta di flettere la PIP. Poi si flette la MCP e si retesta la PIP.",
    positive: "PIP non flette con MCP estesa ma flette con MCP flessa = retrazione muscoli intrinseci.",
  },
  {
    name: "Allen test",
    district: "vascular",
    purpose: "Valuta perfusione arteriosa della mano (radiale/ulnare).",
    procedure: "Il paziente chiude il pugno. L'esaminatore comprime entrambe le arterie radiale e ulnare. Il paziente apre la mano (pallida). Si rilascia una arteria alla volta.",
    positive: "Mancato ripristino del colorito entro 5 secondi rilasciando un'arteria = occlusione/insufficienza di quel ramo.",
    sensitivity: "Variabile",
  },
  {
    name: "Froment",
    district: "wrist",
    purpose: "Identifica deficit del nervo ulnare (adduttore del pollice).",
    procedure: "Il paziente afferra un foglio tra pollice e indice (laterale). L'esaminatore tira il foglio.",
    positive: "Flessione compensatoria dell'IF del pollice = paralisi adduttore del pollice (nervo ulnare).",
  },
  {
    name: "OK sign (nervo interosseo anteriore)",
    district: "wrist",
    purpose: "Identifica lesione del nervo interosseo anteriore (ramo del mediano).",
    procedure: "Si chiede al paziente di fare il segno 'OK' con pollice e indice formando un cerchio.",
    positive: "Incapacità a flettere IF del pollice o DIP dell'indice (pinch a piatto invece che a cerchio) = lesione del nervo interosseo anteriore.",
  },
];
